name: workflowtrigger

on:
  repository_dispatch:
    types: [run_my_workflow]
      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "Payload field is ${{ github.event.client_payload.mydata }}"
    - run: echo "Event triggered by ${{ github.event_name }} event"
    
